room = "home"
music = "002_Morning_Evening"
enemy_chance = 0.0
background = "background/room_home"

[layout]
left_x = 0
right_x = 640
top_y = 0
bottom_y = 480

[[layout.objects]]
sprite = "env/home_plant"
r = { x = 444, y = 114, w = 9, h = 21 }

[[layout.objects]]
sprite = "env/home_poster"
r = { x = 328, y = 103, w = 25, h = 37 }

[[layout.objects]]
sprite = "env/home_nightstand"
r = { x = 208, y = 195, w = 18, h = 42 }

[[layout.objects]]
sprite = "env/home_wardrobe"
r = { x = 241, y = 172, w = 38, h = 68 }

[[layout.objects]]
sprite = "env/home_bed"
r = { x = 142, y = 205, w = 62, h = 90 }

[[layout.objects]]
sprite = "env/home_chair"
r = { x = 431, y = 278, w = 19, h = 42 }

[[layout.objects]]
sprite = "env/home_table"
r = { x = 461, y = 242, w = 39, h = 98 }

[[layout.collision]]
r = { x = 300, y = 140, w = 220, h = 20 }

[[layout.collision]]
r = { x = 280, y = 140, w = 20, h = 80 }

[[layout.collision]]
r = { x = 120, y = 200, w = 160, h = 20 }

[[layout.collision]]
r = { x = 120, y = 220, w = 20, h = 120 }

[[layout.collision]]
r = { x = 120, y = 340, w = 220, h = 20 }

[[layout.collision]]
r = { x = 320, y = 360, w = 80, h = 20 }

[[layout.collision]]
r = { x = 380, y = 340, w = 140, h = 20 }

[[layout.collision]]
r = { x = 500, y = 160, w = 20, h = 180 }

[[layout.collision]]
r = { x = 459, y = 244, w = 43, h = 98 }

[[layout.collision]]
r = { x = 429, y = 304, w = 23, h = 18 }

[[layout.collision]]
r = { x = 203, y = 204, w = 79, h = 34 }

[[layout.collision]]
r = { x = 140, y = 219, w = 66, h = 78 }

[[layout.triggers]]
seq = ["(I used to like this view.)"]
r = { x = 440, y = 140, w = 40, h = 20 }

[[layout.triggers]]
seq = ["(It's my bed.)"]
r = { x = 140, y = 219, w = 66, h = 78 }

[[layout.triggers]]
seq = ["(I don't feel like putting real clothes on.)"]
r = { x = 239, y = 204, w = 42, h = 35 }

[[layout.triggers]]
seq = ["(A poster a friend gave me as a gift.)"]
r = { x = 320, y = 140, w = 40, h = 20 }

[[layout.triggers]]
seq = """
local q = flag("quest/mail")

if q == 2 then
    write("(There is an absence of dust where my mail key used to be.)")
elseif q == 1 then
    write("(My mailbox key is resting atop the nightstand.)")
    if choice({"Take it", "Leave it"}) == 0 then
        write([[
(Might as well check.)
You grabbed the /!MAILKEY/.
]])
        set_flag("quest/mail", 2)
    else
        write("(I probably don't have mail anyway.)")
    end
else
    write("(There are several extra pillowcases inside the drawer.)")
end
"""
r = { x = 206, y = 221, w = 22, h = 18 }

[[layout.transitions]]
name = "to_hallway"
enter_dir = "South"
to_room = "home_hallway"
to_transition = "from_home"
default = false
is_save_point = false
r = { x = 340, y = 340, w = 40, h = 20 }

[[layout.transitions]]
name = "from_hallway"
enter_dir = "North"
default = true
is_save_point = false
r = { x = 340, y = 320, w = 40, h = 20 }
