room = "home_lobby"
music = "002_Morning_Evening"
background = "background/room_home_lobby"

[layout]
left_x = 0
right_x = 0
top_y = 0
bottom_y = 0

[[layout.objects]]
sprite = "env/home_lobby_mail"
r = { x = 302, y = 145, w = 96, h = 75 }

[[layout.objects]]
sprite = "env/home_lobby_mail"
r = { x = 401, y = 145, w = 96, h = 75 }

[[layout.objects]]
sprite = "env/elevator"
r = { x = 181, y = 179, w = 79, h = 81 }

[[layout.collision]]
r = { x = 120, y = 240, w = 60, h = 20 }

[[layout.collision]]
r = { x = 120, y = 260, w = 20, h = 120 }

[[layout.collision]]
r = { x = 140, y = 360, w = 60, h = 20 }

[[layout.collision]]
r = { x = 240, y = 360, w = 280, h = 20 }

[[layout.collision]]
r = { x = 500, y = 200, w = 20, h = 160 }

[[layout.collision]]
r = { x = 300, y = 200, w = 200, h = 20 }

[[layout.collision]]
r = { x = 280, y = 200, w = 20, h = 40 }

[[layout.collision]]
r = { x = 260, y = 240, w = 40, h = 20 }

[[layout.triggers]]
seq = ["(Mailboxes for floors 8-14.)"]
r = { x = 300, y = 200, w = 100, h = 20 }

[[layout.triggers]]
seq = """
local q = flag("quest/mail")
if q == 2 then
    write("You placed the key into the lock and looked inside.")
    write("(There's a letter inside!)")
    write("You got the /!CRUMPLEDLETTER/")
elseif q == 1 then
    write("(I think I left my key in my nightstand.)")
else
    write([[(Mailboxes for floors 1-7. I probably don't have any mail.)
(I think I left my key in my nightstand.)]])
    set_flag("quest/mail", 1)
end
"""
r = { x = 400, y = 200, w = 100, h = 20 }

[[layout.transitions]]
name = "from_elevator_ride"
enter_dir = "South"
default = true
is_save_point = false
r = { x = 180, y = 260, w = 80, h = 20 }

[[layout.transitions]]
name = "to_elevator_ride"
enter_dir = "North"
to_room = "elevator_ride"
to_transition = "enter"
default = false
is_save_point = false
r = { x = 180, y = 240, w = 80, h = 20 }

[[layout.transitions]]
name = "from_outside"
enter_dir = "North"
default = false
is_save_point = false
r = { x = 200, y = 340, w = 40, h = 20 }

[[layout.transitions]]
name = "to_outside"
enter_dir = "South"
to_room = "home_outside"
to_transition = "from_lobby"
default = false
is_save_point = false
r = { x = 200, y = 360, w = 40, h = 20 }
